<? //数据分析
AS_DataRequestProviderNameDataSetProviderDataDatabegin declare ierrCount smallint; szDjBh Varchar(20); iRowCount smallint ; iFlen int ; begin declare iPDh int ; szRBH char(6) ; TempExp Exception ; begin delete from zb_zfpzdjbh; select nvl(Length(''),0) into iFlen from dual; select nvl(max(Substr(djbh,1,6)),'_') into szDJBH from ZB_VIEW_ZFPZ_BB Where Gsdm='001' and KJND='2017' and ZFFSDM='02' and length(djbh) >= 6; if szDJBH='_' then select '000001' into szDJBH from dual ; else if Length(rtrim(szDJBH)) = nvl(Length(''),0) + 6 then select Substr(szDJBH,iFlen+1,6) into szRBH from dual ; select to_char(to_number(szRBH)+1) into szRBH from dual ; while Length(LTrim(RTrim(szRBH)))<6 Loop select '0' || LTrim(RTrim(szRBH)) into szRBH from dual ; end Loop ; select Rtrim('' || szRBH) into szDJBH from dual ; else select '000001' into szDJBH from dual ; end if ; end if; select max(to_number(pdh)) into iPdh from ZB_ZFPZML_Y where gsdm='001' and kjnd='2017' ; if iPDh is null then select 0 into iPDh from dual; end if; insert into ZB_ZFPZDJBH values(szDJBH); 

//以上的部分应该是不变的 除了日期等数据外

insert into ZB_ZFPZML_Y( Gsdm,Kjnd,Pdqj,Pdh,zflb,Djbh,xjbz,zphm,Pdrq,Dzkdm,Ysdwdm, Fkrdm,Fkr,Fkryhbh,Fkzh,Fkrkhyh,Fkyhhh,PJPCHM, Skrdm,Skr,Skryhbh,Skzh,Skrkhyh,Skyhhh, Zy,FJS,lrr_ID,lrr,lr_rq,dwshr_id,dwshr,dwsh_rq,cxbz,bz2,zt,dybz,ZZPZ) select '001', '2017', '201706', to_char(iPDh+1),'0', zfpzdjbh, '0', '_', '20170622', '23', '901006001', '00030005', '遂川县枚江镇财政所（零余额账户）', '00030005', '178157750000004662', '农商行枚江分理处', '012', '_','99900114', '吉安遂川县财政局', '99900114', '190207313396', '中行遂川支行', '005', 'zhaiyao', 0,899,'傅爱琼', to_char(sysdate,'yyyymmdd'), -1,'','', '0' ,'0','0','0','0' from zb_zfpzdjbh ; insert into ZB_ZFPZNR_Y( Gsdm,Kjnd,JHID,ZBID,Pdqj,Pdh,pdxh,zflb,LINKID,zjxzdm,jsfsdm,Yskmdm,Jflxdm,zffsdm,zclxdm,ysgllxdm,zblydm,xmdm,SJWH,BJWH,YWLXDM,XMFLDM,KZZLDM1,KZZLDM2,zbje,yyzbje,kyzbje,JE) values ( '001', '2017', '', '001.2017.0.6183', '201706', to_char(iPDh+1), 1,'0',-1,'9', '2', '2299901', '30299', '02', '0202', '2', '7', '9', '_', '_', '_', '_', '_', '_', 4000, 1, 3999, 1) ; Insert Into ZB_ZFPZNR_Y_MC(GSDM,KJND,ZFLB,PDH,PDQJ,JSFSMC,NEWDYBZ,NEWZZPZ,NEWCXBZ,NEWPZLY,NEWZT,PDXH,DZKMC,XMMC,XMFLMC,YSDWMC,YSDWQC,YWLXMC,ZFFSMC,MXZBWH,MXZBXH,ZBLYMC,ZJXZMC,YSKMMC,YSKMQC,JFLXMC,JFLXQC,ZCLXMC,YSGLLXMC,KZZLMC1,KZZLMC2) Values('001','2017','0',to_char(iPDh+1),'201706','转账','未打印','纸质','正常凭证','正常','正常',1,'乡财股','其他资金','','枚江镇行政','枚江镇行政','','授权支付','公共文号',1657,'其他指标','其他资金','其他支出','其他支出-其他支出-其他支出','其他商品和服务支出','商品和服务支出-其他商品和服务支出','授权支付','乡镇支出','',''); commit; select iPDh+1 into ierrCount from dual ; Exception when others then RollBack; select 0 into ierrCount from dual ; end ; Open :pRecCur for select ierrCount RES,szDJBH DJBH from dual; end; end;




    "DZKDM" => "84"
    "DZKMC" => "预算股乡镇组"
    "YSDWDM" => "901006001"
    "YSDWMC" => "枚江镇行政"
    "ZJXZDM" => "11"
    "ZJXZMC" => "公共财政预算资金"
    "ZFFSDM" => "02"
    "YSKMDM" => "2130299"
    "YSKMMC" => "其他林业支出"
    "JFLXDM" => "39999"
    "JFLXMC" => "其他支出"
    "ZCLXDM" => "0202"
    "ZCLXMC" => "授权支付"
    "XMDM" => "9"
    "XMMC" => "其他资金"
    "ZBLYDM" => "21"
    "ZBLYMC" => "本级财力安排"
    "ZJLYMC" => "201707037361"
    "YKJHZB" => "4500"
    "YYJHJE" => "4500"
    "KYJHJE" => "0"
    "YSGLLXDM" => "2"
    "YSGLLXMC" => "乡镇支出"
    "NEWYSKMDM" => "2130299"
    "ZBID" => "001.2017.0.7054"
    "ZY" => "2017年林改转移支付乡用"
    "ZBWH" => "公共文号"

    MXZBXH
    MXZBWH
    1657


KZZLDM1

    //-------------------------------

  // 26 => array:89 [
  //   "GSDM" => "001"
  //   "KJND" => "2017"
  //   "MXZBLB" => "0"
  //   "MXZBBH" => "3283"
  //   "MXZBWH" => "2016年预算数据"
  //   "MXZBXH" => "97"
  //   "ZZBLB" => "0"
  //   "ZZBBH" => "438"
  //   "FWRQ" => "20170101"
  //   "DZKDM" => "84"
  //   "YSDWDM" => "901006008"
  //   "ZBLYDM" => "82"
  //   "YSKMDM" => "2120199"
  //   "ZJXZDM" => "11"
  //   "JFLXDM" => "_"
  //   "ZCLXDM" => "_"
  //   "XMDM" => "3001"
  //   "ZFFSDM" => "_"
  //   "JE" => "7235"
  //   "ZY" => "2016年预算数据"
  //   "LRR_ID" => "1108"
  //   "LRR" => "用友维护组"
  //   "LR_RQ" => "20170101"
  //   "XGR_ID" => "-1"
  //   "CSR_ID" => "1108"
  //   "CSR" => "用友维护组"
  //   "CS_RQ" => "20170102"
  //   "HQBZ" => "0"
  //   "HQWCBZ" => "0"
  //   "SHJBR_ID" => "-1"
  //   "SHR_ID" => "1108"
  //   "SHR" => "用友维护组"
  //   "SH_RQ" => "20170102"
  //   "SNJZ" => "0"
  //   "NCYS" => "0"
  //   "BNZA" => "0"
  //   "BNZF" => "0"
  //   "BNBF" => "0"
  //   "ZBYE" => "7235"
  //   "SJLY" => "1"
  //   "YZBLB" => "0"
  //   "YSGLLXDM" => "1"
  //   "ZBZT" => "0"
  //   "TZBZ" => "0"
  //   "JZRQ" => "20171231"
  //   "ZBID" => "001.2017.0.3283"
  //   "ZBIDWM" => "001.2016.0.3212"
  //   "DCBZ" => "否"
  //   "DCRID" => "-1"
  //   "STAMP" => "2"
  //   "OAZT" => "0"
  //   "TZH" => "-1"
  //   "JZR_ID" => "-1"
  //   "PZFLH" => "0"
  //   "JZR_ID1" => "-1"
  //   "PZFLH1" => "0"
  //   "DJZT" => "0"
  //   "SCJHJE" => "0"
  //   "DYBZ" => "0000000000"
  //   "YWLXDM" => "_"
  //   "XMFLDM" => "_"
  //   "SJWH" => "_"
  //   "KZZLDM1" => "_"
  //   "KZZLDM2" => "_"
  //   "ASHR_ID" => "1108"
  //   "ASHR" => "用友维护组"
  //   "ASH_RQ" => "20170102"
  //   "ASHJD" => "-1"
  //   "AXSHJD" => "-2"
  //   "ASFTH" => "否"
  //   "ZBLB" => "正常"
  //   "DZKMC" => "预算股乡镇组"
  //   "ZBLYMC" => "集中支付16年结余"
  //   "YSDWMC" => "枚江乡规划所"
  //   "YSDWQC" => "枚江乡规划所"
  //   "YSKMMC" => "其他城乡社区管理事务支出"
  //   "YSKMQC" => "城乡社区支出-城乡社区管理事务-其他城乡社区管理事务支出"
  //   "ZJXZMC" => "公共财政预算资金"
  //   "XMMC" => "人员公务费"
  //   "YSGLLXMC" => "县本级支出"
  //   "HQNAME" => "不会签"
  //   "ZZBWH" => "2016年预算数据"
  //   "ZZBXH" => "25"
  //   "YWLXMC" => "_"
  //   "XMFLMC" => "_"
  //   "KZZLMC1" => "_"
  //   "KZZLMC2" => "_"
  //   "ZFFSLB" => "无区分"
  //   "DYBZ1" => "未打印"
  //   ];
